version: "3" # docker-compose version
services:
  db:
    build: ./docker/db
    image: hatnotehistory_db
    ports:
      - "5432:5432" # default for postgres
    restart: unless-stopped
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    image: hatnotehistory_web
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on: 
      - db
